name: Rust
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Update apt cache
      run: sudo apt-get update
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: rustfmt
      run: cargo fmt -- --check
    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D warnings
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Update apt cache
      run: sudo apt-get update
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: cargo test --all --verbose
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update apt cache
      run: sudo apt-get update
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose